"""update_embedding_dim_to_768

Revision ID: 9aa582132277
Revises: cf159fc72f72
Create Date: 2026-05-02 12:29:36.243037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9aa582132277'
down_revision: Union[str, None] = 'cf159fc72f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Set embedding to NULL before altering the dimension
    op.execute("UPDATE methods SET embedding = NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('methods', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('methods', 'origin_domain',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('methods', 'problem_class',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('methods', 'equation_class',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('methods', 'constraint_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('methods', 'python_implementation',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('methods', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=384),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('methods', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=384),
               existing_nullable=True)
    op.alter_column('methods', 'python_implementation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('methods', 'constraint_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('methods', 'equation_class',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('methods', 'problem_class',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('methods', 'origin_domain',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('methods', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
