"""Initial migration

Revision ID: cf159fc72f72
Revises: 
Create Date: 2026-04-01 07:23:31.306475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cf159fc72f72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('origin_domain', sa.String(length=255), nullable=False),
    sa.Column('appears_in', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('mathematical_core', sa.Text(), nullable=False),
    sa.Column('problem_class', sa.String(length=255), nullable=False),
    sa.Column('equation_class', sa.String(length=255), nullable=False),
    sa.Column('constraint_type', sa.String(length=255), nullable=False),
    sa.Column('cross_domain_example_1', sa.Text(), nullable=True),
    sa.Column('cross_domain_example_2', sa.Text(), nullable=True),
    sa.Column('where_analogy_breaks', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('runnable', sa.Boolean(), nullable=True),
    sa.Column('python_implementation', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('complexity_level', sa.String(length=50), nullable=True),
    sa.Column('typical_use_cases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('known_limitations', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('primitives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('method_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('primitives')
    op.drop_table('methods')
    # ### end Alembic commands ###
